global:
#  registry url only this part
  dockerRegistryUrl: ""
#  image name
  image:
# image version
  imageVersion:
  namespace:
  hpa:
    enabled: "false"
    minReplicas:
    maxReplicas:
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 50
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 120
        policies:
          - type: Percent
            value: 20
            periodSeconds: 60
      scaleUp:
        policies:
          - type: Percent
            value: 80
            periodSeconds: 30
  datasource:
    migration:
      enabled: "false"
      image: ''
      secretRefs: {}
      configMapRefs: {}
  application:
    name:
    port: 8080
    labels: {}
    replicaCount: 1
    annotations: {}
    ingress:
      rewriteTarget: /$2
      targetPath:
      annotations:
        nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_502 http_503 http_504"
        nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
    prometheus:
      actuatorPath: /actuator/prometheus
      scrape: true
      actuatorPort: 8081
    deployment:
      livenessProbe:
        httpGet:
          path: /actuator/health/liveness
          port: ahttp
          scheme: HTTP
        initialDelaySeconds: 0
        timeoutSeconds: 10
        periodSeconds: 20
      readinessProbe:
        httpGet:
          path: /actuator/health/readiness
          port: ahttp
          scheme: HTTP
        initialDelaySeconds: 10
        timeoutSeconds: 10
        periodSeconds: 30

      configMapRefs: {}
      secretRefs: {}
    resources:
      java:
        opts: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=70.0 -XX:+ExitOnOutOfMemoryError"
      requests:
        memory: 256Mi
        cpu: 1000m
      limits:
        memory: 256Mi
        cpu: 1000m