{
 "title": "Pod monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "app",
    "label": "application",
    "query": {
     "query": "label_values({namespace=\"$namespace\"},service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "app" },
  {
   "title": "Pod running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace=\"$namespace\", pod=~\"$app.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 22, "x": 2, "y": 1 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$app.*\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$app.*\"}",
     "legendFormat": "usage-{{pod}}"
    },
    {
     "expr": "container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"$app.*\"}",
     "legendFormat": "max-{{pod}}"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$app.*\"}",
     "legendFormat": "usage-{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU trotling",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\", pod=~\"$app.*\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP server  RPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"$namespace\", pod=~\"$app.*\"}[5m]))",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "HTTP client requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(irate(http_client_requests_seconds_count{namespace=\"$namespace\", pod=~\"$app.*\"}[5m]))",
     "legendFormat": "sum"
    }
   ]
  }
 ]
}