info:
  component: ${spring.application.name}
server:
  port: ${PORT:3333}
  tomcat:
    threads:
      max: 1000
feign:
  hystrix:
    enabled: true
  circuitbreaker:
    enabled: true
feign-clients:
  account-service:
    url: http://localhost:3334
spring:
  profiles:
    include: stash
  application:
    name: customer-service
  security:
    user:
      name: user
      password: password
      roles: ACTUATOR
  cloud:
    kubernetes:
      reload:
        enabled: false
        mode: polling
        period: 5000
      loadbalancer:
        enabled: false
    discovery:
      enabled: false

  rabbitmq:
    host: localhost
    username: user
    password: password
    port: 5672

management:
  tracing:
    sampling:
      probability: 1
    propagation:
      type: b3_multi
      consume: b3_multi
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  endpoints:
    web:
      exposure:
        #      new feature most endpoints from http layer not allowed
        include: "*"
