@Library("jenkins-util")_

generalCi(
    branch: "boot-2.5.8-and-java-17-migration",
    scmUrl: "git@github.com:Merdoc97/microservices-spring-sample.git",
    mavenModule: "admin-dashboard/",
    pathToAppChart: "/infra/charts/admin",
    helmReleaseName: "admin",
    kubernetesNameSpace: "microservice",
    generateReport: true
)
