apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.name}}
  minReplicas: {{.Values.scaling.minReplicas}}
  maxReplicas: {{.Values.scaling.maxReplicas}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{.Values.scaling.cpu.utilization}}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 20
          periodSeconds: 60
    scaleUp:
      policies:
        - type: Percent
          value: {{.Values.scaling.cpu.utilization}}
          periodSeconds: 10
