@Library("jenkins-util")_

generalCi(
    branch: "jenkins-pipelines-example",
    scmUrl: "git@github.com:Merdoc97/microservices-spring-sample.git",
    mavenModule: "turbine/",
    pathToAppChart: "/infra/charts/turbine",
    helmReleaseName: "turbine-service",
    kubernetesNameSpace: "microservice",
    generateReport: true
)
