info:
  component: ${spring.application.name}
server:
  port: ${PORT:3334}

spring:

  application:
    name: account-service
  security:
    user:
      name: user
      password: password
      roles: ACTUATOR
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
    discovery:
      enabled: true
  rabbitmq:
    host: localhost
    username: user
    password: password
    port: 5672
  zipkin:
    compression:
      enabled: true
    base-url: http://localhost:9411
    enabled: true
    service:
      name: ${spring.application.name}
    sender:
      type: rabbit
    encoder: json_v2
  sleuth:
    sampler:
      probability: 1.0
    messaging:
      enabled: true
      rabbit:
        enabled: true

ribbon:
  eureka:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        #      new feature most endpoints from http layer not allowed
        include: "*"
  endpoint:
    hystrix:
      stream:
        enabled: false

feign:
  hystrix:
    enabled: true