@Library("jenkins-util")_

generalCi(
    branch: "jenkins-pipelines-example",
    scmUrl: "git@github.com:Merdoc97/microservices-spring-sample.git",
    mavenModule: "account-service/",
    pathToAppChart: "/infra/charts/account-service",
    helmReleaseName: "account-service",
    kubernetesNameSpace: "microservice",
    generateReport: true
)
