@Library("jenkins-util")_

releaseDockerAndHelmCi(
    branch: "boot-2.5.8-and-java-17-migration",
    scmUrl: "git@github.com:Merdoc97/microservices-spring-sample.git",
    mavenModule: "gateway-service/",
    pathToAppChart: "/infra/charts/gateway",
    helmReleaseName: "api-gateway",
    kubernetesNameSpace: "microservice",
    generateReport: true,
    useSonar: false,
    tagOnly: true
)
