apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.global.application.name}}-volume
  labels:
    type: local
spec:
  storageClassName: "hostpath"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi